### ISSUE TITLE
Documentation update to connect to MS Chat bot

### ISSUE THREAD

**Issue by awilu** [NGRP/node-red-contrib-viseo#63]
Get an "envoi impossible" from the MS test window but all my settings have been made as expected by the wiki.

**Comment by JpEncausse** [comment]
Well it's a glitch,

In the BotBuilder node you should leave it as is, it will bind the server to the Node-RED port (1880). Otherwise it will start a dedicated restify server (we will remove that feature because ExpressJS works very well)

Then instead of setting the 1880 in the Bot Framework you should setup NGinx and perform a redirect from 80 to 443 to 1880 so you will have a clean install

**Comment by awilu** [comment]
Thanks for your quick answer.
But I already setup my nginx with the default value that you provide (with the redirection chain) in the wiki.

**Comment by JpEncausse** [comment]
Ok so,  `https://my_domain.com/api/v1/messages` that mean the route is OK

- then create a bot in MSBotFramework, 
- set the callback URL https://my_domain.com/api/v1/messages
- then set theAppId and AppPassword in BotBuilder Node

=> Save and PM2 Restart the server (to be sure)

Test with the WebChat in MSBotFramework you should at least receive a log in the console and if you set a debug node you should see the JSON from the botbuilder message

If OK, create a Facebook Messenger Channel (App & page), etc ...

**Comment by awilu** [comment]
It's all done.
In my webchat in MSbotframewirk, I still have the same message +
"There was an error sending this message to your bot: HTTP status code GatewayTimeout" on the connector's dashboard.
Nothing in my debug screen from Viseo

**Comment by JpEncausse** [comment]
Hum, that's weird, it's like the bot can't reach your server. i'll try to make a step-by-step video this week-end

**Comment by awilu** [comment]
Bug closed. Work after a reboot (viseo side) and reconnection on MSFT side. Thanks for your help
