### ISSUE TITLE
Cannot find module 'request-promise'

### ISSUE THREAD

**Issue by JBX028** [NGRP/node-red-contrib-viseo#93]
Hi,

Looks like there is an issue when I try to install node-red-contrib-viseo-dialogflow.
This module is not part of package.json. What should I do? I'll check deeper in the code tomorrow but in case someone know the answer already, I will not waste my time for nothing.
Worst case, I will try to install request and or request-promise.

![image](https://user-images.githubusercontent.com/88729/44684206-c5574c00-aa48-11e8-8dec-0ccc99a9bc14.png)

- node-red v.0.18.7
- node v8.11.3
- npm 5.6.0

Thanks in advance :)

**Comment by JpEncausse** [comment]
You should install Viseo Bot Maker from this project:
https://github.com/NGRP/node-red-viseo-bot

Which contains a package.json with all our modules because installing single modules can trigger issues. For instance if multiple module require the same module with different version it can became a big mess (npm dedup can help)

BTW, yes we may have forget to add request or request-promise to it's package.json. YOu can install it manualy.

**Comment by JBX028** [comment]
Hi,
Thanks for your reply. Works fine now.
